### ISSUE TITLE
Make add-from-github default workflow faster

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/cardano-haskell-package-repo#3]
Ideas:

- Just call `git commit` straightaway
    - Add an option to not do so if necessary
- Call `git format-patch` instead of providing a commit message file and a timestamp on stdout, so you can just `git am` it
    - Bonus points: `git am` can do a sequence of commits, so we can put each package addition into its own commit

I think my preferred workflow would be:
- Commit by default, one commit per package added
- Optionally don't commit, and produce output with `format-patch`

**Comment by andreabedini** [comment]
I have implemented the first option in d1519512d782dfd3d67775641b6c9bc86ec0fefd. The second requires a git commit anyway so it wouldn't have been as straightforward.
